apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-python
  labels:
    app: hello-world-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-python
  template:
    metadata:
      labels:
        app: hello-world-python
    spec:
      containers:
        - name: hello-world-python
          image: your-dockerhub-username/hello-world-python:latest
          ports:
            - containerPort: 5000
